### ISSUE TITLE
Rank is not sequential when updating

### ISSUE THREAD

**Issue by chevinbrown** [dmarkow/ecto_ranked#17]
```
defmodule UserImage do
  use Ecto.Schema
  import Ecto.Changeset
  import EctoRanked


  schema "image_reviews" do
    belongs_to(:image, Image)
    belongs_to(:user, User)

    field(:rank, :integer)
    field(:position, :any, virtual: true)
  end

  def changeset(image_review, attrs) do
    image_review
    |> cast(attrs, [:image_id, :position])
    |> validate_required([:image_id])
    |> set_rank(scope: [:user_id])
  end
end
```
When updating positions, I get some pretty wild swings. Here is an example of steps I follow:
```
1. Repo.get(UserImage, 1) |> UserImage.changeset(%{position: 0}) |> Repo.update
#=> position is 0
2. Repo.get(UserImage, 2) |> UserImage.changeset(%{position: 1}) |> Repo.update
#=> position is 1073741824
```
Is this expected behavior? It's technically in order, but it's not sequential.

**Comment by dmarkow** [comment]
This is the expected behavior. The idea is to reduce database operations when you insert and rearrange records. In your example, adding something after UserImage 1 (position 0) would put it at roughly 500,000,000, without having to update UserImage 2. Adding something before UserImage 1 would make the new item roughly -1,000,000,000 and wouldn't require changing UserImage 1 or 2. Every insert or update looks for the halfway point between the two neighbors where you want to put the record and uses that. It only has to change other entries (in which case is rebalances the entire dataset) when there is no gap.

With a sequential list, adding something after UserImage 1 would require adding 1 to UserImage 2's position. Or deleting UserImage 1 would require subtracting 1 from UserImage 2's position, and so on.

However this does mean that you really only use the rank column for ordering your results, not for identifying exact positions in the list. In Elixir, if you wanted actual index numbers of your dataset, you could use something like [Enum.with_index/2](https://hexdocs.pm/elixir/1.12/Enum.html#with_index/2)

This library is effectively an Elixir/Ecto clone of https://github.com/brendon/ranked-model in Ruby/ActiveRecord. That project's README and https://www.getharvest.com/blog/2011/02/a-new-rails-positioning-library-rankedmodel explain the idea a bit more.

**Comment by chevinbrown** [comment]
10-4, @dmarkow, I figured that was the expected operation, but there's a part of me that wants a nice, neat list. 🙂 

Thanks!
