### ISSUE TITLE
set_rank fails bad argument in arithmetic expression

### ISSUE THREAD

**Issue by jesuisbonbon** [dmarkow/ecto_ranked#3]
im trying to do a set_rank on a many_to_many relation.

```  
  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  
  schema "user_tasks" do
    field :rank,            :integer
    field :position,        :any, virtual: true

    belongs_to :task,       Task
    belongs_to :user,       User
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:position])
    |> set_rank(scope: [:task_id, :user_id])
  end
```

this is where is mod my changeset
```
     ch = from(t in UserTasks, where: t.user_id == ^user.id and t.task_id == ^task.id)
       |> Repo.one
       |> Ecto.Changeset.change

     UserTasks.changeset(ch, %{position: pos |> String.to_integer})
        |> Repo.update
```

I'm getting an error:

```
** (exit) an exception was raised:
    ** (ArithmeticError) bad argument in arithmetic expression
        (ecto_ranked) deps/ecto_ranked/lib/ecto_ranked.ex:81: EctoRanked.rank_between/4
        (ecto_ranked) deps/ecto_ranked/lib/ecto_ranked.ex:33: anonymous fn/2 in EctoRanked.set_rank/2
        (ecto) lib/ecto/repo/schema.ex:403: anonymous fn/2 in Ecto.Repo.Schema.run_prepare/2
```

I was fiddling around, it seems that the finder function is generating a wrong query

in defp find_neighbors pos > 0 it calls in my case [] -> {get_current_last(cs, options), @max}
the get_current_last returns a nil, because the query is like 

```
from u in UserTasks, where: u.task_id == ^"366768fd-7852-4920-8a3a-31854cb20e0c", where: u.user_id == ^"03719ee4-63f7-427e-b658-245de16406e5", where: u.id != ^"65d0c873-bff4-4ea2-83cd-36b6612459e1"
```

the u.id != causes a nil return, I think this should be == instead of != in this case

**Comment by dmarkow** [comment]
The `!=` is correct -- it's trying to find two **other** items/ranks to move your data between. If `get_current_last` is returning nil, that's because the item is already at the end of the list and you're trying to move it to an even higher position (which you can't do). For example, if you have this list:

- Item 1 (position 0)
- Item 2 (position 1)

You can't say "move Item 1 to position 2" because there is no position 2, only 0 and 1.

I'll compare to how other libraries have handled, but for now, make sure you're only providing valid positions.
